Martynenko branch
IlyaOrlov/PythonCourseATIS pull request #10
Opened 2022-01-09 13:47 UTC by ismartynenko

Домашняя работа на новогодних праздниках

2022-01-09 14:21 UTC, IlyaOrlov requested changes
Хорошо, но есть некоторые замечания!

2022-01-09 14:21 UTC, IlyaOrlov commented on Practice/ismartynenko/practice3_palindrom.py
> +    if word.find(backword) != -1:
Нужно учесть случай, когда слово начинается с большой буквы, например, "Довод", "Топот" или имя "Алла". И почему бы просто не сравнить word и backword (мне такой вариант кажется более понятным и наглядным)?

2022-01-09 14:21 UTC, IlyaOrlov commented on Practice/ismartynenko/practice3_stop.py
> +str = input("Input a number: ")
Не стоит использовать названия стандартных функций и ключевые слова Python для именования переменных (str - стандартная функция для приведения к строковому типу).

2022-01-09 14:21 UTC, IlyaOrlov commented on Practice/ismartynenko/practice3_stop.py
> +while str.find("STOP") == -1:
В задании еще предусмотрены варианты "Stop" и "stop" для выхода из цикла.

2022-01-09 14:21 UTC, IlyaOrlov commented on Practice/ismartynenko/tanks.py
> +    def move(tank, key, speed):
Согласно PEP8 первый аргумент метода объекта нужно называть self.

2022-01-09 14:21 UTC, IlyaOrlov commented on Practice/ismartynenko/tanks.py
> +    while not Tank.move(a, key_a, speed):
Методы экземпляра класса Tank можно вызывать проще: a.move(key_a, speed) и в стр. 66: b.move(key_b, speed).

2022-01-10 11:41 UTC, IlyaOrlov requested changes
ОК. Но есть вопросы.

2022-01-10 11:41 UTC, IlyaOrlov commented on Practice/ismartynenko/practice3_stop.py
> +while stroka_l.find(stopkey) == -1:
Можно сделать немножко поизящней: ```while stopkey not in stroka_l:```

2022-01-10 11:41 UTC, IlyaOrlov commented on Practice/ismartynenko/practice3_palindrom.py
> +check(word.lower())
Можно, конечно, и так. Но тогда, если я захочу применить функцию к каким-либо предустановленным данным - check("Топот") - то мне каждый раз нужно будет приводить их к нижнему регистру вне функции. Вопрос тут в том, является ли приведение к нижнему регистру неотъемлемой частью проверки на палиндром, или нет. Если - да, то lower() надо выполнять внутри функции. Но, возможно, у вас есть возражения...

2022-01-10 11:59 UTC, ismartynenko commented on Practice/ismartynenko/practice3_palindrom.py
> +check(word.lower())
Возражений нет. Схалтурил)
Перенесу внутрь функции

2022-01-10 12:31 UTC, IlyaOrlov commented on Practice/ismartynenko/practice3_palindrom.py
> +check(word.lower())
ОК, еще один момент. word и backword - это фактически одни и те же буквы, поэтому лучше сначала привести word к нижнему регистру, а потом вычислять backword:
```python
word = word.lower()
backword = word[::-1]
```
Тогда lower() достаточно будет вызвать только один раз. Ну или можно обойтись без backword:
```python
if word == word[::-1]:
```

2022-01-10 18:59 UTC, IlyaOrlov approved these changes
Все отлично!

2022-01-10 18:59 UTC, merged