Решение Задачки с детьми
IlyaOrlov/PythonCourseATIS pull request #15
Opened 2022-01-12 11:41 UTC by ismartynenko

Изменил тип данных

2022-01-12 21:37 UTC, IlyaOrlov reviewed
Всё хорошо! Есть небольшие замечания/дополнения.

2022-01-12 21:37 UTC, IlyaOrlov commented on Practice/ismartynenko/children_example_fix.py
> +            children += tuple([child])
Сделать из child кортеж можно проще (главное - запятая):
```python
chilldren += child,
# или
chilldren += (child,)
# или
chilldren += tuple(child,)
```

2022-01-12 21:37 UTC, IlyaOrlov commented on Practice/ismartynenko/children_example_fix.py
> +DEFAULT = {
Вы правильно нашли ошибку! Предложенное решение также является рабочим. Но поскольку children в цикле часто меняется, а чтоб поменять кортеж, надо каждый раз создавать новый кортеж с полным (!) копированием старого, то данное решение нельзя назвать оптимальным. Список - все-таки лучше подходит, если требуется часто вносить изменения. А для того, чтобы не использовался один и тот же список children для всех записей, нужно просто однократно (!) делать его копию (где-нибудь в строке 12). 
Это как с файлом pep8task.py в первом задании. В папке Tasks лежит сам файл, каждый слушатель копирует его в свою папку и может делать с копией все, что захочет. При этом, оригинальный файл остается в исходном состоянии.

2022-01-12 21:37 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_1_FizzBuzz.py
> +    if cond1 and cond2 is True:
Если у значений переменных заведомо логический тип, то is True писать необязательно. Можно просто: if cond1 and cond2:
А еще здесь можно было просто написать if i % 15 == 0:)

2022-01-12 21:37 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_1_FizzBuzz.py
> +    cond1 = i % 3 <= 0
Почему <=, а не ==?

2022-01-12 21:37 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_2_digit.py
> +digit = input("Введите 5-ти значное число: ")
Здесь все хорошо. Можно еще схлопнуть строки 1-4 в две, используя моржовый оператор (:=) для привязки digit к input (это позволит в одном выражении и digit определять и его длину с 5 сравнивать. Получится примерно так:
```python
while ... != 5
    pass
...
```

2022-01-12 21:38 UTC, IlyaOrlov requested changes
Всё хорошо! Есть небольшие замечания/дополнения.

2022-01-17 18:22 UTC, IlyaOrlov requested changes
Пара совсем небольших замечаний!

2022-01-17 18:22 UTC, IlyaOrlov commented on Practice/ismartynenko/children_example_fix.py
> +    children = list(DEFAULT.copy())
Отлично! Но копия списка - это и так список, поэтому list() - здесь лишний.

2022-01-17 18:22 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_1_FizzBuzz.py
> +    elif cond1 is True:
Здесь и в строке 8 тоже можно без is True.

2022-01-17 21:16 UTC, ismartynenko commented on Practice/ismartynenko/children_example_fix.py
> +    children = list(DEFAULT.copy())
Если убрать _list_, то _children_ определяется как Словарь. Я так понимаю что потому _DEFAULT_ является словарем.
А мы делаем его копию. И дополнительно начинает ругаться на 17-ую строку на метод _append_, неприменимый к словарям

Заметил что нужны изменения в 18 строке:
`    people.append({'name': name, 'surname': surname, 'children': children[3:]})`

2022-01-17 21:35 UTC, IlyaOrlov commented on Practice/ismartynenko/children_example_fix.py
> +    children = list(DEFAULT.copy())
Да, точно. Вот в чем проблема. В этой строке не нужно копировать весь DEFAULT, а только DEFAULT ['children'], который и так является списком.

2022-01-18 09:10 UTC, ismartynenko commented on Practice/ismartynenko/children_example_fix.py
> +    children = list(DEFAULT.copy())
Что то я не соображу как это сделать. Может наводка какая то есть?

2022-01-18 09:11 UTC, ismartynenko commented on Practice/ismartynenko/children_example_fix.py
> +    children = list(DEFAULT.copy())
Была мысль брать список, а потом обнулять его перед следующей итерацией, но вроде прошлые решения изящнее были...

2022-01-18 11:24 UTC, IlyaOrlov commented on Practice/ismartynenko/children_example_fix.py
> +    children = list(DEFAULT.copy())
Вы практически все верно сделали, только брать здесь надо конкретно список: children = DEFAULT['children'].copy()
DEFAULT - словарь, DEFAULT['children'] - значение словаря по ключу 'children'.

2022-01-18 11:34 UTC, IlyaOrlov requested changes
Оставил несколько комментариев.

2022-01-18 11:34 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_3_sort.py
> +    mini = min(arr[i:])
Решение рабочее, но есть пара нюансов) arr[i:] - это, фактически, копирование подсписка, что может быть затратным по времени и памяти. Также мы здесь идем по списку в поиске минимума, а потом (в строке 4) снова идем по списку в поиске индекса этого минимума. Если вместо min и index написать свой цикл поиска индекса минимального элемента в списке, начиная с i, то получится гораздо более быстрое решение.

2022-01-18 11:34 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_4_tab.py
> +stroka_with_tabs = "\tHello.\t-\tHi!\t"
Хорошо. Но нужно еще добавить вывод результата на экран и предусмотреть работу с файлом.

2022-01-20 12:15 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_3_sort.py
> +    arr2_sorted.append(arr.pop(minimal(arr)))
Отлично! Это решение быстрее. Небольшое примечание на будущее: если бы в задании было требование ограничиться одним списком (без вспомогательных), то вместо перемещения элемента в новый список достаточно было сделать перестановку:
```python
    arr[i], arr[min_i] = arr[min_i], arr[i]
```

2022-01-20 12:17 UTC, IlyaOrlov requested changes
Еще одно небольшое замечание.

2022-01-20 12:17 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_4_tab.py
> +fo = open("practice4_4_tab.txt")
Для работы с файлами лучше использовать оператор with.

2022-01-21 12:05 UTC, ismartynenko commented on Practice/ismartynenko/practice4_3_sort.py
> +    arr2_sorted.append(arr.pop(minimal(arr)))
Беру на заметку

2022-01-24 08:10 UTC, IlyaOrlov requested changes
Старые замечания исправлены. Но есть немножко новых)

2022-01-24 08:10 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_6_matrix.py
> +            delete_index = i
Надо предусмотреть случай, когда элемент встречается в различных столбцах. Их индексы надо будет сложить в некоторую структуру данных, чуть-чуть ее доработать и потом по ней удалить столбцы из матрицы. Т.е. почти то же самое, что сейчас, только с несколькими индексами.

2022-01-24 08:10 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_6_matrix.py
> +for k, v in enumerate(matrix):
Зачем здесь k и enumerate?

2022-01-24 08:10 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_2_pupil.py
> +    sec = random.randint(3, 6)
Код 15-17 надо поместить в solve_task() для Pupil.

2022-01-24 08:10 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_2_pupil.py
> +    Man.solve_task()
Это правильно, что вы здесь обращаетесь к методу родительского класса, а не переписываете код. Только обращаться лучше через super(). Это позволяет не завязываться на конкретные имена классов. При множественном наследовании, когда у нескольких родителей есть одноименные методы, нам может потребоваться вызвать конкретный метод конкретного класса через имя этого класса. Но если явной необходимости в этом нет, лучше использовать super().

2022-01-24 08:10 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_2_pupil.py
> +print(e1.name, Man.solve_task())
Статические методы тоже можно вызывать через имя экземпляра: e1.solve_task()

2022-01-24 08:10 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_2_pupil.py
> +class Man:
Можно его просто импортировать из practice5_1_classMan.py

2022-01-24 12:25 UTC, IlyaOrlov requested changes
Отлично! Осталось единственное замечание.

2022-01-24 12:25 UTC, IlyaOrlov commented on Practice/ismartynenko/practice4_6_matrix.py
> +            delete_index.append(i)
Хорошо, но что если удаляемое число встречается дважды в одном столбце? Не попытается алгоритм удалить этот столбец дважды? Проблему легко предотвратить, если использовать для delete_index **на этапе добавления** более подходящую структуру данных.

2022-01-24 18:14 UTC, IlyaOrlov approved these changes
Отличная работа!

2022-01-24 18:14 UTC, merged