Часть заданий по четвертой лекции.
IlyaOrlov/PythonCourseATIS pull request #17
Opened 2022-01-15 07:26 UTC by fruittrainings

Обратите внимание на комментарий в строке 71 файла lecture_04_task_04.py.

2022-01-15 11:55 UTC, IlyaOrlov requested changes
Есть замечания по оптимизации используемых алгоритмов.

2022-01-15 11:55 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04/lecture_04_task_01.py
> +        if int(number) % 15 == 0:
Слишком много приведений к int одной и той же строки. Лучше один раз написать number = int(number).

2022-01-15 11:55 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04/lecture_04_task_02.py
> +        for item in five_digit_number:
То же самое можно сделать быстрее, если НЕ создавать новый список, а просто идти по исходной строке.

2022-01-15 11:55 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04/lecture_04_task_02_decorated.py
> +        return None
Лучше если подменяющая функция сохранит интерфейс подменяемой. Если подменяемая функция возвращает **a**, то (если это не противоречит логике декоратора) и wrapper должен возвращать **a**.

2022-01-15 11:55 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04/lecture_04_task_03.py
> +        aux_list = lst[i:] # это подсписок исходного списка начиная с элемента i включительно,
Здесь каждый раз происходит копирование подсписка, что неоптимально с точки зрения затрат времени и памяти. Все равно же все изменения мы выполняем только в главном списке lst.
Понятно, что это обеспечивает корректную работу index и min. Но использование вместо них еще одного самописного цикла по тому же списку, начиная с i + 1-го элемента, позволит избавиться от указанных накладных расходов.

2022-01-15 11:55 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04/lecture_04_task_04.py
> +    whitespace_switch(str4) # failed строка содержит ТОЛЬКО символы табуляции, и интерпретатор,
Просто табуляция при выводе практически не отличается от пробелов. Чтоб сохранить при выводе представление табуляции в виде \t, надо использовать функцию repr (отладочный вывод). Например:
```python
s = "Hello\tBye"
print(repr(s))
```
Выведется: ```'Hello\tBye'```

2022-01-15 11:55 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04/lecture_04_task_04.py
> +        if line.find(" " * 4) == line.find("\t") == -1:
Для line и для string_or_file слишком много вызовов find c одними и теми же данными. Лучше один раз вызвать find с разными аргументами и сохранить результаты в переменных для последующего использования в сравнениях.

2022-01-15 22:46 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04/lecture_04_task_01.py
> +        if int(number) % 15 == 0:
Спасибо, исправил.

2022-01-15 22:47 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04/lecture_04_task_02.py
> +        for item in five_digit_number:
Спасибо, исправил.

2022-01-15 22:47 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04/lecture_04_task_02_decorated.py
> +        return None
Спасибо, исправил.

2022-01-15 22:52 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04/lecture_04_task_03.py
> +        aux_list = lst[i:] # это подсписок исходного списка начиная с элемента i включительно,
Не могу понять, как можно решить задачу засчет добавления еще одного цикла, однако, поразбиравшись с методом index, получил более короткое решение, которое не требует создания вспомогательного списка.

2022-01-15 22:54 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04/lecture_04_task_04.py
> +    whitespace_switch(str4) # failed строка содержит ТОЛЬКО символы табуляции, и интерпретатор,
Спасибо за информацию. Как оказалось, программа работала некорректно из-за логической ошибки во второй ветке обработчика IOError - исправил ее.

2022-01-15 22:54 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04/lecture_04_task_04.py
> +        if line.find(" " * 4) == line.find("\t") == -1:
Спасибо, исправил.

2022-01-16 09:46 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04/lecture_04_task_03.py
> +        aux_list = lst[i:] # это подсписок исходного списка начиная с элемента i включительно,
Проблема в том, что lst[i+1:] - это фактически тоже копирование подсписка (как и любой срез). И в этом выражении:
```python
lst[i], lst[lst.index(min(lst[i+1:]), i+1)] = lst[lst.index(min(lst[i + 1:]), i + 1)], lst[i]
```
этих копировании стало два, не говоря уже о повторных вызовах index и min.
Помните задачу с нахождением максимального элемента, которую мы решали на занятии? При помощи вложенного цикла здесь мы должны сделать фактически то же самое, только:
1) искать будем минимум, 
2) запоминать будем не только само число, но и его индекс (чтоб потом проще было выполнять перестановку),
3) поиск будем выполнять, начиная с i + 1-го элемента (поэтому для вложенного цикла лучше использовать цикл while).
Это решение лучше еще из-за того, что мы сразу, за один проход по подсписку, будем находить и минимум, и его индекс. Тогда как, применяя min и index, мы сначала идем по списку в поисках минимума, а потом снова идем по этому же списку, определяя индекс этого минимума.

2022-01-16 10:17 UTC, IlyaOrlov requested changes
Еще несколько замечаний.

2022-01-16 10:17 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_05.py
> +    for item in kwargs:
Пример классный))) Небольшое замечание по коду: если идти по kwargs.items(), то можно сразу получать и ключ, и значение без необходимости дополнительного поиска по ключу: kwargs[item].
И лучше, чтоб функция возвращала stri, а не просто выводила на консоль. Тогда результат, к примеру, можно будет сразу отправлять по почте или в телеграм прямо в этом же скрипте:)

2022-01-16 10:17 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_04.py
> +        initial_file = open(string_or_file, "r")
Стоит попробовать работать с файлами через менеджер контекста with.

2022-01-16 10:17 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_04.py
> +            print("%r" % new_line)
В одном скрипте лучше использовать один способ вывода: либо процент, либо форматную строку. Возможно, это субъективное мнение, но так код становится проще для восприятия.

2022-01-16 10:17 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_06.py
> +                break
Если искомое число встречается в нескольких столбцах, надо удалить их все.

2022-01-16 20:25 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04/lecture_04_task_03.py
> +        aux_list = lst[i:] # это подсписок исходного списка начиная с элемента i включительно,
Спасибо, переделал.

2022-01-16 20:26 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_05.py
> +    for item in kwargs:
Спасибо, переделал.

2022-01-16 20:26 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_04.py
> +            print("%r" % new_line)
Спасибо, переделал.

2022-01-16 20:30 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_04.py
> +        initial_file = open(string_or_file, "r")
В данном примере, считаю, затруднительным использовать менеджер контекта with, поскольку между открытиями файлов для чтения и записи происходит создание наименования файла записи с привязкой к текущим дате и времени.

2022-01-16 20:42 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_06.py
> +                break
Спасибо, переделал.

2022-01-16 21:18 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_04.py
> +        initial_file = open(string_or_file, "r")
Необязательно ограничиваться одним with:)
```python
        with open(string_or_file, "r") as initial_file:
            print("Найден файл:")
            date_to_insert_into_file_name = str(datetime.datetime.today())[:19].replace(" ", "_").replace(":", "-")
            name_of_new_output_file = "output_file_created_on_"+date_to_insert_into_file_name+"_based_on" + \
                                      initial_file.name+".txt"
            with open(name_of_new_output_file, "w") as output_file:
                line = initial_file.readline()
                new_line = ""

                line_find_four_spaces = line.find(" " * 4)
                line_find_tab = line.find("\t")
                if line_find_four_spaces == line_find_tab == -1:
                    print(rf"{line}")
                    print("Результат: переданный файл не содержит символов табуляции или четырех пробелов подряд")
                elif line_find_four_spaces != -1 and (line_find_tab == -1 or line_find_four_spaces < line_find_tab):
                    new_line = line.replace(" " * 4, "\t")
                    print(rf"{new_line}")
                    print(f"Результат: каждые четыре пробела подряд в переданном файле были заменены "
                          f"на символы табуляции и сохранены в {name_of_new_output_file}")
                elif line_find_four_spaces == -1 or line_find_tab < line_find_four_spaces:
                    new_line = line.replace("\t", " " * 4)
                    print(rf"{new_line}")
                    print(f"Результат: каждый символ табуляции в переданном файле был заменен "
                          f"на четыре пробела подряд и сохранен в {name_of_new_output_file}")
                output_file.write(new_line)
            # initial_file.close()
            # output_file.close()
        print('-' * 30)

```

2022-01-16 21:22 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_04.py
> +        initial_file = open(string_or_file, "r")
Спасибо, а не подскажете в какой блок можно засунуть обработку исключения ниже, в котором происходит обработка строк?

2022-01-16 21:27 UTC, IlyaOrlov requested changes

2022-01-16 21:27 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_03.py
> +        while i < j < len(lst):
Т.к. i - положительное целое число, j всегда только увеличивается на 1 и начальное его значение i + 1, то j всегда будет больше i (т.е. достаточно оставить while j < len(lst):).

2022-01-16 21:27 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_06.py
> +        for col in columns_to_remove:
Нужно учесть варианты, когда удаляемое число встречается дважды в одной строке или одном столбце. Например, (удаляем 7):
```python
lst0 = [
    [7, 2, 7],
    [4, 5, 6],
    [7, 8, 1]
]
```
Чтоб это учесть, нужно немножко обработать columns_to_remove перед удалением.

2022-01-16 21:32 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_04.py
> +        initial_file = open(string_or_file, "r")
Отлов и обработку исключения не нужно вносить в блоки with. Если initial_file не открылся - то мы и в блок with не зайдем. Если initial_file открылся, но произошла проблема с открытием output_file (например, нет прав на запись), то во внутренний with мы не попадаем, а при выходе из внешнего with (даже по исключению) initial_file закроется (что не произошло бы без with).
На самом деле я определял границы блоков with по строкам открытия и закрытия файлов.

2022-01-16 21:32 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_03.py
> +        while i < j < len(lst):
Спасибо, исправил.

2022-01-16 22:19 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_04.py
> +        initial_file = open(string_or_file, "r")
Странно, как раз в том случае, если файл отсутствует получаю следующую ошибку:
Traceback (most recent call last):
  File "C:\Users\fedor\Documents\Cources\PythonDevelopment\PythonCourseATIS\Practice\frumyantsev\lecture_04_task_04.py", line 86, in <module>
    whitespace_switch(file0)
  File "C:\Users\fedor\Documents\Cources\PythonDevelopment\PythonCourseATIS\Practice\frumyantsev\lecture_04_task_04.py", line 11, in whitespace_switch
    with open(string_or_file, "r") as initial_file:
FileNotFoundError: [Errno 2] No such file or directory: 'lecture_04_task_04_initial_test_file_00'

2022-01-16 22:43 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_04.py
> +        initial_file = open(string_or_file, "r")
Все таки пришлось обернуть блоки with в try.

2022-01-16 22:43 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_06.py
> +        for col in columns_to_remove:
Переделал.

2022-01-17 07:58 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_04.py
> +        initial_file = open(string_or_file, "r")
Всё верно. With здесь только для обеспечения своевременного освобождения занятого ресурса (закрытия открытого файла). Если мы хоти отлавливать исключения - без try не обойтись.

2022-01-17 08:00 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_04_task_06.py
> +        for col in columns_to_remove:
Отлично! Еще одно небольшое улучшение: если columns_to_remove изначально сделать множеством, то set(columns_to_remove) в стр.24 можно не выполнять - там и так будут уникальные элементы.

2022-01-17 08:22 UTC, fruittrainings commented on Practice/frumyantsev/lecture_04_task_06.py
> +        for col in columns_to_remove:
Спасибо, исправил.

2022-01-17 10:01 UTC, IlyaOrlov approved these changes
Отличная работа!

2022-01-17 10:01 UTC, merged