Задания по 2,3,4 лекции + разбор pep8task
IlyaOrlov/PythonCourseATIS pull request #18
Opened 2022-01-17 18:11 UTC by ZloiGaMeR

Илья, проверьте пожалуйста задания.
Спасибо!

2022-01-17 18:26 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec2_3.py
> +class GameSetup:
Упаковать константы в отдельный класс - это отличная идея!

2022-01-17 18:45 UTC, IlyaOrlov requested changes
Прекрасно! Особенно с классом. 
Есть только небольшие замечания.

2022-01-17 18:45 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec3_1.py
> +        number = number + temp
Можно попроще: number += temp

2022-01-17 18:45 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec3_2.py
> +    if word.lower() == word[::-1].lower():
Дважды одни и те же буквы приводятся к нижнему регистру. Стоит оптимизировать.

2022-01-17 18:45 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_1.py
> +    if i % 15 == 0:
Для числа, которое делится нацело на 15, будут выполняться и строки 8 и 10, хотя это очевидно лишнее. Если сделать проверку на 15 первой, а остальные if заменить на elif, число лишних проверок и присваиваний можно сократить.

2022-01-17 18:45 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec3_3.py
> +    if a > b:
Если b > a, мы всегда можем поменять их местами и сократить количество кода в этой функции.

2022-01-17 18:45 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec3_3.py
> +        if int(temp) > x:
Небольшая оптимизация: temp = int(temp) - и у нас будет один вызов int() вместо двух.

2022-01-17 18:45 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_3.py
> +        index = in_arr.index(min(in_arr[i:]), i)
Как мы уже обсуждали, срез in_arr[i:] приводит к создании копии списка. К тому же, здесь нам приходится сначала идти по списку в поисках минимума, а потом идти почти по тому же списку в поисках индекса этого минимума. Ведь можно сразу получать и минимум, и индекс, если идти по списку во вложенном цикле.

2022-01-17 18:45 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_5.py
> +str = "sdsf fdfsd refsdf w fsgsd wefvcxvsdfv"
Не следует использовать названия стандартных функций для именования переменных (речь о str).

2022-01-17 18:45 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_6.py
> +                break
Если искомое число встречается дважды в одной строке в разных столбцах, то удалить нужно оба столбца. Например, (удаляем 2):
```python
listoflists = [
    [2, 3, 4, 2],
    [6, 3, 6, 8],
    [1, 9, 7, 5]
]
```

2022-01-21 19:41 UTC, IlyaOrlov requested changes
Еще несколько предложений по улучшению кода.

2022-01-21 19:41 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_3.py
> +        for j in range(len(in_arr)):
В этом цикле не стоит бежать с начала списка. Надо начать с i + 1. Тогда итераций будет меньше.

2022-01-21 19:41 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_1.py
> +    pr = i
А это можно в else поместить.

2022-01-21 19:41 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_6.py
> +        while count in range(len(i)):
while count < len(i) вычисляется быстрее и, как мне кажется, точнее отражает смысл count (индекс проверяемого столбца).

2022-01-21 19:41 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_6.py
> +                count = 0
Чтоб не начинать каждый раз с нуля, можно попробовать упростить код:
```python
if i[count] == number:
    for k in matrix:
        print(k.pop(count))
else:
    count += 1
```

2022-01-25 14:05 UTC, IlyaOrlov requested changes
Остались небольшие замечания. Также нужно сделать git pull origin main и git push, чтоб 
 в этом Pull Request не было чужих файлов (например, Practice/frumyantsev/lecture_05_warmup_01.py )

2022-01-25 14:05 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec5_1.py
> +        time.sleep(random.randint(3, 6))
После сна Pupil должен сделать "то же, что делает Man в этом же методе".

2022-01-25 14:05 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec5_2.py
> +            f = open(self.filepath, "r")
С файлом лучше работать через with.

2022-01-25 14:05 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec5_2.py
> +        self.filepath = tempfile.mktemp()
Должен ли у пользователей данного класса быть доступ к имени файла, который используется в этом классе?

2022-01-25 14:06 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec4_3.py
> +    for i in range(len(in_arr[1::])):
И снова мы копируем подсписок in_arr[1::]. Это лишнее.

2022-01-26 05:57 UTC, ZloiGaMeR commented on Practice/a.belyantsev/Lec5_2.py
> +            f = open(self.filepath, "r")
Согласен, но в задании есть сточка "Не забудьте закрывать файл после чтения или записи".  Так как with делает это автоматически и "забыть" не возможно, я подумал что требуется реализация именно через Open.

2022-01-28 19:55 UTC, IlyaOrlov requested changes
Пара небольших замечаний по Lec5_1.py и Lec6_2.py

2022-01-28 19:55 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec5_1.py
> +        print("I'm not ready yet")
ОК, только лучше через super обратиться к родительскому методу. Да, выгода от этого здесь неочевидна. Но суть в том, что если логика родителя поменяется, то без обращения к родительскому методу это логику придется менять у все наследников, которые **"должны делать то же, что и Man"**.

2022-01-28 19:55 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec6_2.py
> +def multiplier(m=1, source=None):
Проблема найдена правильно, но решение можно улучшить. source по умолчанию можно оставить, но сделать его кортежем. Также использование enumerate лишнее, т.к. i не используется. И result можно сразу списковым выражением генерировать из source.

2022-01-28 19:55 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec6_3.py
> +        self._enter_time = time.time_ns()
Отлично! +100500 за protected атрибут!

2022-01-31 09:32 UTC, IlyaOrlov approved these changes
Отлично! Учтены все нюансы!

2022-01-31 09:33 UTC, merged