Два примера из разминки в начале лекции 5 и 2 задания по фабрике танков.
IlyaOrlov/PythonCourseATIS pull request #19
Opened 2022-01-19 07:39 UTC by fruittrainings

2022-01-19 12:14 UTC, IlyaOrlov requested changes
Оставил несколько предложений по оптимизации.

2022-01-19 12:14 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_05_tanks/tank_factory.py
> +        tank._speed = passed_speed
Чтоб обойти ограничение на доступ к защищенным/закрытым полям, в классе создают специальные методы (например, get_power() и set_power()), которым целиком передается ответственность за работу со скрытыми полями. Иногда, нужно открыть доступ к атрибуту только для чтения, тогда создают только get_-метод (геттер), а set_-метод (сеттер) не создают. Сегодня мы рассмотрим т.н. properties - синтаксический сахар, позволяющий добавлять эти геттеры и сеттеры более изящно.

2022-01-19 12:14 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_05_warmup_01.py
> +    for i in range(len(arguments)):
Т.к. индекс здесь не важен, я бы предпочел обходить контейнер через **for i in arguments:**. Такая реализация, кстати, будет работать и для множеств, и для словарей (т.е. для неупорядоченных структур).

2022-01-19 12:46 UTC, fruittrainings commented on Practice/frumyantsev/lecture_05_warmup_01.py
> +    for i in range(len(arguments)):
Спасибо, исправил.

2022-01-19 20:00 UTC, IlyaOrlov requested changes

2022-01-19 20:00 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_01.py
> +        self.name = input("Введите имя: ")
Лучше все-таки задавать имя вне класса, чтоб можно было создавать экземпляр Man, например, с каким-то предопределенным именем: m1 = Man("Иван")

2022-01-19 20:00 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_02.py
> +        print("I'm not ready yet")
Если какой-то код наследника очевидным образом дублирует код родителя, лучше явно вызвать код родителя через super (речь конкретно о строке 19). Тогда при необходимости поменять логику, достаточно будет внести изменения в код родителя.

2022-01-24 08:32 UTC, IlyaOrlov requested changes
Все исправлено на отлично! Есть замечания по lecture_05_task_03.py: хотя property часто используются для обеспечения доступа к защищенному/закрытому атрибуту, их можно применять и без привязки к каким-либо атрибутам (как в данной задаче).

2022-01-24 08:32 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_03.py
> +            pass
Нужен ли этот pass (еще и после return)?

2022-01-24 08:32 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_03.py
> +        self._filepath = self._filepath
В чем смысл этого присваивания?

2022-01-24 08:32 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_03.py
> +    _content = ''
Есть ли смысл в существовании атрибута _content? Property в данном примере позволяют работать напрямую с файлом.

2022-01-24 12:19 UTC, fruittrainings commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_03.py
> +            pass
Спасибо. Убрал это недоразумение.

2022-01-24 12:19 UTC, fruittrainings commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_03.py
> +        self._filepath = self._filepath
Убрал - это тоже недоразумение.

2022-01-24 12:27 UTC, fruittrainings commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_03.py
> +    _content = ''
Спасибо. Закомментировал/убрал/заменил строки с _content - действительно без этого поля можно обойтись. Однако, если бы я читал такой код, не зная о том, что в вычисляемых свойствах можно обойтись без одноименного атрибута, то мне было бы сложнее понять его.  Получается, поля классов можно определять в их методах по мере необходимости (например _filepath) или вовсе не создавать, если необходимости нет (_content)...

2022-01-24 12:36 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_05_tanks/lecture_05_task_03.py
> +    _content = ''
> Однако, если бы я читал такой код, не зная о том, что в вычисляемых свойствах можно обойтись без одноименного атрибута, то мне было бы сложнее понять его.

Замечу, что ЗНАЯ о том, что в вычисляемых свойствах можно обойтись без одноименного атрибута, понять код (в частности, зачем здесь вообще используется этот атрибут) не менее сложно:)

> Получается, поля классов можно определять в их методах по мере необходимости (например _filepath) или вовсе не создавать, если необходимости нет (_content)...

Да, именно так!

2022-01-24 12:38 UTC, IlyaOrlov approved these changes
Теперь всё супер! Учтены даже нюансы.

2022-01-24 12:38 UTC, merged