Практика 5-3 WrapStrToFile
IlyaOrlov/PythonCourseATIS pull request #20
Opened 2022-01-27 11:29 UTC by ismartynenko

Не могу понять откуда None в выводе, намекните:
```
File doesn't exist
None
test str
text 2
```

2022-01-27 12:58 UTC, fruittrainings commented
Похоже, это return ветки except геттера content.

2022-01-27 16:33 UTC, IlyaOrlov commented
> Похоже, это return ветки except геттера content.

Так точно)
При выполнении строки: 
```python
print(wstf.content) # Output: File doesn't exist
```
Код в стр. 18 печатает "File doesn't exist", а в самой стр.35 печатается то, что вернулось из wstf.content (а это как раз None).
Если не придираться к тому, что по условию задачи должно возвращаться 'Файл еще не существует', то никакой ошибки в этом нет.

2022-01-27 16:35 UTC, IlyaOrlov requested changes
Все ОК, но есть вопросы по коду.

2022-01-27 16:35 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_3_wrap.py
> +        with open(self.filepath, "w+") as fp:
Почему здесь режим "w+"?

2022-01-27 16:35 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_3_wrap.py
> +        self.filepath = mktemp()
Должен ли атрибут filepath быть доступен вне класса WrapStrToFile?

2022-01-27 19:01 UTC, ismartynenko commented on Practice/ismartynenko/practice5_3_wrap.py
> +        with open(self.filepath, "w+") as fp:
Согласен, достаточно только "w".
P.S. Но что интересно - скрипт не работает, если в данном месте указать "r+", хотя мы обсуждали что это даст права и на чтение и запись

2022-01-27 19:55 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_3_wrap.py
> +        with open(self.filepath, "w+") as fp:
Ну так "r+" - это И чтение, И запись. А несуществующий файл открыть на чтение нельзя)

2022-01-27 19:57 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_3_wrap.py
> +        self.filepath = mktemp()
global? Та-а-к... а почему он должен быть доступен вне класса?

2022-01-28 08:22 UTC, ismartynenko commented on Practice/ismartynenko/practice5_3_wrap.py
> +        with open(self.filepath, "w+") as fp:
Понял, я думал что с плюсом, это доступны, чтение, запись - любое из этого.

2022-01-28 08:36 UTC, ismartynenko commented on Practice/ismartynenko/practice5_3_wrap.py
> +        self.filepath = mktemp()
просто по другому не работает)
пробовал убрать Global,  и в других методах обращаться через nonlocal - чет нифига - ошибки

2022-01-28 09:03 UTC, IlyaOrlov commented on Practice/ismartynenko/practice5_3_wrap.py
> +        self.filepath = mktemp()
Использовать self было правильным решением, т.к. filepath - т.е. путь к файлу, где хранить контент - это личное дело класса WrapStrToFile. Пользователи класса вообще могут не знать о существовании этого файла (для чего мы property и применяем). Своим вопросом я намекал на то, чтоб сделать этот атрибут защищенным.

2022-01-28 17:56 UTC, IlyaOrlov approved these changes
Теперь все ОК!

2022-01-28 17:57 UTC, merged