Практика 6-1, 6-2, 6-3
IlyaOrlov/PythonCourseATIS pull request #21
Opened 2022-01-30 18:20 UTC by ismartynenko

1, 2, и 3-ье задание из 6-ой лекции

2022-01-31 09:27 UTC, IlyaOrlov requested changes
Все хорошо, но осталась пара замечаний.

2022-01-31 09:27 UTC, IlyaOrlov commented on Practice/ismartynenko/practice6_3.py
> +        self.end_time = time()
Должны ли end_time и start_time быть доступны вне TestManager?

2022-01-31 09:27 UTC, IlyaOrlov commented on Practice/ismartynenko/practice6_2.py
> +def multiplier(m, source=None):
Проблема все еще воспроизводится на таком примере (аргументы одинаковые, а вывод разный):
```python
lst = [1, 2]
print(multiplier(12, lst))
print(multiplier(12, lst))
```
Стоит сделать source неизменяемым, или делать result из source сразу списковым выражением.

2022-02-01 21:21 UTC, IlyaOrlov requested changes
Оставил еще один комментарий.

2022-02-01 21:21 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_razminka_1.py
> +class Reader:
Решение правильное! Особенно понравился изящный обход ветки **else: raise StopIteration** через break. Но стоит сделать код чуть более универсальным:
1. Путь к файлу лучше сделать аргументом конструктора (чтоб итератор мог работать с любыми файлами).
2. Если файл НЕ заканчивается символом параграфа, последняя строка не должна теряться. Т.е. когда мы поняли, что char == "", нужно установить какой-нибудь специальный флаг (т.е. еще одну переменную), вернуть текущее содержимое buffer и только на следующей итерации (если этот спец. флаг установлен) сделать raise StopIteration.

2022-02-02 11:52 UTC, IlyaOrlov requested changes
Итератор доработан отлично. Оставил только небольшой комментарий по улучшению кода. 
Также осталось замечание к practice6_2.py
И нужно сделать git pull origin main и git push, т.к. в этот Pull Request попали чужие файлы.

2022-02-02 11:52 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_razminka_1.py
> +        if self.eof:
Стоит сделать эту проверку до инициализации буфера и чтения из файла, потому что, если мы достигли конца файла,  эти операции выполнять бессмысленно.
И eof лучше тоже сделать защищенным (с одним подчеркиванием), т.к. вне класса он не используется.

2022-02-02 12:10 UTC, ismartynenko commented
> 

6-2 вроде ранее исправлял все замечания???

2022-02-02 12:35 UTC, IlyaOrlov commented
> > 
> 
> 6-2 вроде ранее исправлял все замечания???

ОК. Сама означенная проблема исправлена. Но мы получаем result сначала как копию списка, а потом эту копию еще и переделываем. Лучше сразу списковым выражением создавать result из source, и без enumerate там вполне можно обойтись.

2022-02-02 22:05 UTC, ismartynenko commented
> > > 
> > 
> > 
> > 6-2 вроде ранее исправлял все замечания???
> 
> ОК. Сама означенная проблема исправлена. Но мы получаем result сначала как копию списка, а потом эту копию еще и переделываем. Лучше сразу списковым выражением создавать result из source, и без enumerate там вполне можно обойтись.

Сделал через списковое выражение, и убрал лишний enumerate.

Вопрос, как эту задачу можно было решить способом:
`Стоит сделать source неизменяемым`
Immutable у нас tuple, и frozenset. Последний явно не подходит.

2022-02-03 07:27 UTC, IlyaOrlov commented
> > > > 
> > > 
> > > 
> > > 6-2 вроде ранее исправлял все замечания???
> > 
> > 
> > ОК. Сама означенная проблема исправлена. Но мы получаем result сначала как копию списка, а потом эту копию еще и переделываем. Лучше сразу списковым выражением создавать result из source, и без enumerate там вполне можно обойтись.
> 
> Сделал через списковое выражение, и убрал лишний enumerate.
> 
> Вопрос, как эту задачу можно было решить способом: `Стоит сделать source неизменяемым` Immutable у нас tuple, и frozenset. Последний явно не подходит.

А tuple подходит)
```python
def multiplier(m=1, source=(1, 2, 3)):
    return [i * m for i in source]
```
В получившейся реализации (где source и так не поменяется) объявление source по умолчанию кортежем (а не списком) дает пользователям функции дополнительную информацию и гарантии.

2022-02-03 12:10 UTC, IlyaOrlov approved these changes

2022-02-03 12:10 UTC, merged