Задания из контольной со *
IlyaOrlov/PythonCourseATIS pull request #24
Opened 2022-02-06 19:26 UTC by ZloiGaMeR

Илья, добрый вечер! Доделал все задания со * из контрольной. Можете глянуть пожалуйста?
Спасибо!

2022-02-06 20:36 UTC, IlyaOrlov requested changes
Хорошо. Но есть существенные замечания.

2022-02-06 20:36 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_3.py
> +        return (self.number_of_rubls + self.number_of_pennies) + (other.number_of_rubls + other.number_of_pennies)
Если мы складываем (умножаем, вычитаем) числа, то в результате у нас получается число. Здесь мы складываем экземпляры Money. Очевидно, в итоге тоже должен получится экземпляр Money. Это позволит, например, выполнить такое сложение: m1 + m2 + m3 (где m1, m2, m3 -  экземпляры класса Money).

2022-02-06 20:36 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_4.py
> +def myrange(stop, step=1, start=0):
Очень хотелось бы, чтоб порядок аргументов совпадал с заданным: start, stop, step.

2022-02-06 20:36 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_4.py
> +            shutil.copy(os.path.join(source, file), destination)
А как же использование copyfile?

2022-02-06 20:36 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_4.py
> +    out_str = args[0]
Можно сразу принимать out_str как отдельный аргумент: def myformat(out_str, *args)

2022-02-07 20:39 UTC, IlyaOrlov requested changes
Еще комментарий по Money

2022-02-07 20:39 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_3.py
> +        _m = Money(0, 0)
Для локальной переменной, существующей только внутри функции, нижние подчеркивания не нужны. Это несколько затрудняет восприятие.
И наверное, объект лучше инициализировать готовыми значениями. А то вдруг при расчетах какие-нибудь исключения возникнут, а объект мы уже создали. Лучше так:
```python
r = self.number_of_rubls + other.number_of_rubls
k = self.number_of_pennies + other.number_of_pennies
return Money(r, k)
```
Ну и не помешало бы, когда копеек больше сотни, перекинуть их в рубли. А при вычитании, наоборот, занять у рублей!

2022-02-09 18:38 UTC, IlyaOrlov requested changes
copydir - супер! По остальным см. замечания.

2022-02-09 18:38 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_4.py
> +        return out
Наверное, лучше один return, чем два в стр. 33 и 38. Да и код в блоках if и else очень похожий...

2022-02-09 18:38 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_4.py
> +    out = [start, ]
Всегда ли стоит возвращать start? Например, для вызова myrange(1, 10, -1).

2022-02-10 16:28 UTC, IlyaOrlov requested changes
Пара небольших замечаний

2022-02-10 16:28 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_4.py
> +        return print("Step should not be 0")
return print - это выглядит странно)

2022-02-10 16:28 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_3.py
> +        if pennies % 1 == 0:
А в каких случаях остаток от деления на 1 не равен 0?

2022-02-11 08:17 UTC, IlyaOrlov requested changes

2022-02-11 08:17 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec7_warmup1.py
> +    def __delete__(self, instance):
\_\_delete\_\_ используется для удаления атрибутов [см. тут](https://www.geeksforgeeks.org/python-__delete__-vs-__del__/#:~:text=Both%20__delete__%20and,commonly%20used%20for%20operator%20overloading.) В данном примере он не вызовется. Здесь нужен деструктор: \_\_del\_\_

2022-02-11 11:06 UTC, ZloiGaMeR commented on Practice/a.belyantsev/Exeam_4.py
> +        return print("Step should not be 0")
Согласен, убрал.

2022-02-11 11:06 UTC, ZloiGaMeR commented on Practice/a.belyantsev/Exeam_3.py
> +        if pennies % 1 == 0:
Если число имеет дробную часть. Не самая удачная проверка на int)) Переделал на if type(pennies) is int или лучше if isinstance(pennies, int): ?

2022-02-11 11:06 UTC, ZloiGaMeR commented on Practice/a.belyantsev/Lec7_warmup1.py
> +    def __delete__(self, instance):
Понял, спасибо!

2022-02-11 12:02 UTC, IlyaOrlov commented on Practice/a.belyantsev/Exeam_3.py
> +        if pennies % 1 == 0:
Разница с type в том, что isinstance проверяет на принадлежность иерархии типов, а type - на строгое соответствие. Здесь не принципиально, что использовать. isinstance(pennies, int) выглядит изящней.

2022-02-11 12:05 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-02-11 12:05 UTC, merged