Задача №3 и №9 к экзамену
IlyaOrlov/PythonCourseATIS pull request #25
Opened 2022-02-07 14:24 UTC by ismartynenko

2022-02-07 20:43 UTC, IlyaOrlov requested changes
Есть некоторые замечания!

2022-02-07 20:43 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_3.py
> +    if stop > 0:
Хорошо, но еще нужно учитывать знак step, иначе не работают следующие примеры:
res = my_range(20, 10, -1)
res = my_range(-20, -10, 1)

2022-02-07 20:43 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_9.py
> +salary_sum = w1.salary + w2.salary
Следует сделать name, age и salary защищенными и обращаться к ним через соответствующие методы.

2022-02-08 13:47 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_9.py
> +salary_sum = w1.salary + w2.salary
Защищенный - это одно подчеркивание. Два подчеркивания - это закрытый. Если требуется ограничить доступ к атрибуту только извне, то надо использовать именно защищенные атрибуты. Текущее же решение может привести к таким эффектам. Допустим, мы захотим добавить в Worker такой метод:
```python
    def show_info(self):
        return f"I'm {self.__name}. My age is {self.__age}"
```
Попытка вызова этого метода:
```python
print(w1.show_info())
```
приведет к ошибке:
```
Traceback (most recent call last):
  File "C:\example.py", line 40, in <module>
    print(w1.show_info())
  File "C:\example.py", line 25, in show_info
    return f"I'm {self.__name}. My age is {self.__age}"
AttributeError: 'Worker' object has no attribute '_Worker__name'
```
Понятно, почему?

2022-02-08 13:54 UTC, IlyaOrlov requested changes
Остались замечания по exam_6.py и exam_9.py

2022-02-08 13:54 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_9.py
> +    def setSalary(self, salary):
Если используете property, тогда этот метод стоит сделать сеттером, методы переименовать просто в salary и то же самое сделать для name и age. Это будет уже не по заданию, но зато код получится в одном стиле.

2022-02-08 13:54 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_6.py
> +    mystr = args[0]
mystr можно сразу сделать отдельным параметром:
```python
def myformat(mystr, *args)
```

2022-02-08 18:28 UTC, ismartynenko commented on Practice/ismartynenko/exam_9.py
> +salary_sum = w1.salary + w2.salary
Полагаю так как приватные __name / __age в родительском классе User.

2022-02-08 19:57 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_9.py
> +salary_sum = w1.salary + w2.salary
Именно. Т.к. приватные атрибуты недоступны в т.ч. в классах наследниках.

2022-02-08 20:04 UTC, IlyaOrlov requested changes
Всё ОК. Небольшой комментарий по exam_6.py

2022-02-08 20:04 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_6.py
> +def myformat(mystr, *args):
Ещё пара штрихов, чтоб сделать эту реализацию myformat идеальной:
1. Лучше, чтоб она возвращала результат, а не выводила его. Тогда вызовы этой функции можно использовать в других выражениях, записывать результат в файл и т.д.
2. Регулярные выражения, которые многократно используются (например, в циклах), лучше предварительно компилировать.

2022-02-09 14:42 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_6.py
> +        return mystr
Лучше один общий return, чем return в стр.13 и 18

2022-02-09 14:57 UTC, ismartynenko commented on Practice/ismartynenko/exam_6.py
> +        return mystr
Согласен. Убрал лишний

2022-02-09 18:11 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-02-09 18:11 UTC, merged