Martynenko branch
IlyaOrlov/PythonCourseATIS pull request #26
Opened 2022-02-10 09:59 UTC by ismartynenko

Лекция 7, задания - 1, 2

2022-02-10 16:19 UTC, IlyaOrlov requested changes
Замечание по practice7_1.py!

2022-02-10 16:19 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_1.py
> +    if b > a:
Чтоб не дублировать код в ветках if и else проще поменять a и b местами, если a > b.
И по стилю: пробелы вокруг "-"!

2022-02-11 08:28 UTC, IlyaOrlov requested changes
Оставил замечания по использованию Human.

2022-02-11 08:28 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_3.py
> +        for _ in people_lst:
read не должен завязываться на глобальные переменные, используемые create, т.к. read может быть запущен вообще в другое время и на другой машине.

2022-02-11 08:28 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_3.py
> +            pickle.dump(people_lst[i].__dict__, f)
Можно один раз задампить весь список people_lst, чем каждую сущность по отдельности.

2022-02-11 18:23 UTC, IlyaOrlov requested changes
Остался вопрос по exam_8.py

2022-02-11 18:23 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_8.py
> +    for i in dir_and_files:
А почему нельзя сразу идти по os.walk(src)? И в строках 16-17 сразу осуществлять копирование файлов?

2022-02-12 07:46 UTC, IlyaOrlov requested changes
Может, и циклы for i in os.walk(src): и for i in dir_and_files: объединить?

2022-02-14 08:09 UTC, IlyaOrlov requested changes
Всё отлично! Есть пара предложений по оптимизации.

2022-02-14 08:09 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_4.py
> +        # Delete files
Если сначала удалять файлы, а потом папки, вероятность того, что папка не пустая, будет меньше.

2022-02-14 08:09 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_4.py
> +    life_time_dir = 120
life_time_dir и life_time_file лучше написать большими буквами, чтоб показать, что это константы.

2022-02-15 21:51 UTC, IlyaOrlov requested changes
Одно небольшое замечание.

2022-02-15 21:51 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_5.py
> +            regexp.append(matchObj)
append здесь не самый лучший выбор, т.к. из-за него в regexp добавляются не отдельные найденные элементы, а списки элементов

2022-02-16 10:11 UTC, IlyaOrlov requested changes

2022-02-16 10:11 UTC, IlyaOrlov commented on Practice/ismartynenko/practice7_5.py
> +for i in regexp:
Чтоб лишний раз по списку не бежать, лучше эту проверку делать непосредственно для matchObj перед стр.9.
i.rstrip() лучше применять к каждому элементу, а потом еще (для тех, у кого i.count('"') == 1) i.rstrip('"'), т.к. некоторые элементы заканчиваются на кавычку с пробелом (```git add" ```)

2022-02-16 13:13 UTC, ismartynenko commented on Practice/ismartynenko/practice7_5.py
> +for i in regexp:
Да, понял. Проглядел

2022-02-16 16:45 UTC, IlyaOrlov approved these changes
Отлично!

2022-02-16 16:45 UTC, merged