Fedor branch 07
IlyaOrlov/PythonCourseATIS pull request #27
Opened 2022-02-11 14:32 UTC by fruittrainings

Начало домашней работы по лекции 7.

2022-02-11 18:18 UTC, IlyaOrlov requested changes
Есть замечания!

2022-02-11 18:18 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_07/lecture_07_task_01.py
> +        if d.weekday() in range(0, 5):
Сравнение на больше/меньше будет быстрее.

2022-02-11 18:18 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_07/lecture_07_task_04.py
> +def file_vanisher(lst_files, lst_dirs):
Концепция решения не соответствует заданию. По условию, программа должна работать, пока ее не остановят. Она должна непрерывно мониторить файлы и папки по указанному пути и проверять, сколько времени прошло с момента их создания (время создания можно узнать через os.path.getctime()).

2022-02-11 22:25 UTC, fruittrainings commented on Practice/frumyantsev/Lecture_07/lecture_07_task_01.py
> +        if d.weekday() in range(0, 5):
Спасибо, исправил.

2022-02-11 22:25 UTC, fruittrainings commented on Practice/frumyantsev/Lecture_07/lecture_07_task_04.py
> +def file_vanisher(lst_files, lst_dirs):
Спасибо, переделал.

2022-02-12 07:51 UTC, IlyaOrlov approved these changes
Отлично! Здорово, что предусмотрели случай, когда папку нельзя удалить из-за оставшихся в ней файлов.

2022-02-12 07:51 UTC, merged