Практика 8-1
IlyaOrlov/PythonCourseATIS pull request #29
Opened 2022-02-22 18:35 UTC by ismartynenko

2022-02-22 21:03 UTC, IlyaOrlov requested changes
Со словарем всё ОК, а вот сортировку стоит оптимизировать.

2022-02-22 21:03 UTC, IlyaOrlov commented on Practice/ismartynenko/practice8_1.py
> +        mini_val = d[lst[0]]
Очевидно, вместо глобальной переменной **lst** лучше использовать локальную **a**.
Также сортировку в строках 10-20 можно сильно упростить, если использовать **a.sort()** с нужным параметром key!

2022-02-23 19:44 UTC, IlyaOrlov requested changes
Всё ещё есть замечания.

2022-02-23 19:44 UTC, IlyaOrlov commented on Practice/ismartynenko/practice8_1.py
> +    # почему не могу сделать так: lst_sort.sort(key=lambda x: lst_sort.count(x)) ???
Без нового списка не обойтись хотя бы потому, что в задании сказано "По заданному списку создать новый список".
Конкретно так **lst_sort.sort(key=lambda x: lst_sort.count(x))** сделать нельзя из-за внутренней реализации алгоритма сортировки (когда мы считаем x в том же списке, который сортируем, это может давать некорректные результаты).
Вариант **lst_sort.sort(key=lambda x: a.count(x))** хороший, но потом всё равно надо отфильтровывать уникальные элементы.
На мой взгляд, идеальное решение - это создание словаря d (как в строках 11-13, только в одно выражение можно записать), затем lst_final = list(d), и потом уже отсортировать lst_final  по ключу d[x] (чтоб лишний раз count не вызывать).

2022-02-23 19:44 UTC, IlyaOrlov commented on Practice/ismartynenko/practice8_2.py
> +class MyIter:
В этом задании надо добавить в класс итератора **еще и** метод типа show_next(n), где n - количество следующих элементов. Этот метод должен работать, по сути, так же, как и метод next, но не должен менять внутреннее состояние итератора (грубо говоря, он не должен менять self._start).

2022-02-23 21:21 UTC, ismartynenko commented on Practice/ismartynenko/practice8_1.py
> +    # почему не могу сделать так: lst_sort.sort(key=lambda x: lst_sort.count(x)) ???
Done.
Но я конечно пока не понимаю как я должен сам приходить к подобным решениям.
Код превратился в 3 строки кода, которые я так понимаю пишутся за 5-10 минут

2022-02-24 07:26 UTC, IlyaOrlov commented on Practice/ismartynenko/practice8_1.py
> +    # почему не могу сделать так: lst_sort.sort(key=lambda x: lst_sort.count(x)) ???
Отлично! На самом деле процесс создания кода всегда состоит из нескольких этапов:
1. Условия задачи.
2. Подбор подходящего алгоритма на основе ранее используемых.
3. Адаптация алгоритма к условиям задачи.
4. Оптимизация алгоритма по читабельности и производительности.
5. Итоговый алгоритм.
Чем больше решенных заданий, тем проще перейти от этапа 1 к этапу 5.
Кстати, даже решенное задание еще можно оптимизировать. Метод count() каждый раз пробегает по всему списку (для каждого уникального элемента). Тогда как ту же задачу можно решить за один проход по списку, просто инкрементируя соответствующие элементы словаря. Это будет в разы быстрее.

2022-02-24 07:53 UTC, IlyaOrlov requested changes

2022-02-24 07:53 UTC, IlyaOrlov commented on Practice/ismartynenko/pep8task_new.py
> +main()
Это можно ещё под ```if __name__ == "__main__"``` поместить, чтоб вообще идеально стало.

2022-02-24 07:53 UTC, IlyaOrlov commented on Practice/ismartynenko/pep8task_new.py
> +from time import *
Нежелательный импорт.

2022-02-24 15:47 UTC, IlyaOrlov approved these changes
Отлично! В practice8_2.py оригинальная идея с сохранением и восстановлением состояния)

2022-02-24 15:47 UTC, merged