Belyantsev branch
IlyaOrlov/PythonCourseATIS pull request #30
Opened 2022-02-24 11:05 UTC by ZloiGaMeR

Задания по 7 лекции на проверку

2022-02-24 15:54 UTC, IlyaOrlov requested changes
Всё ОК! Есть вопрос и комментарий.

2022-02-24 15:54 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec7_3.py
> +import random as _random
А зачем им псевдонимы с нижним подчеркиванием?

2022-02-24 15:54 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec8_1.py
> +    if temp_dict.get(element) is None:
В одну строчку:
```python
temp_dict[element] = temp_dict.get(element, 0) + 1
```

2022-02-24 19:10 UTC, ZloiGaMeR commented on Practice/a.belyantsev/Lec7_3.py
> +import random as _random
Хотел задать тот же вопрос на лекциях и забыл)) Подсмотрел в каком то ютуб ролике по Python. Я так понимаю что это намёк, на то что при импорте данного файла куда либо, не предполагается использование данных библиотек. Они предназначены только для использования в данном конкретном файла. И сделав к примеру импорт from Lec7_3 import * уже не получится воспользоваться функционалом pickle или random, если обращаться без _.

2022-02-24 19:14 UTC, ZloiGaMeR commented on Practice/a.belyantsev/Lec8_1.py
> +    if temp_dict.get(element) is None:
не догадался (

2022-02-25 09:14 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec7_3.py
> +import random as _random
Согласен с объяснением. Но в рабочем коде я такого, если честно, не встречал. Иногда от того же кривого импорта так защищают функции в файле (т.е. объявляют их с нижним подчеркиванием). Но импорты с подчеркиванием - это уже, на мой взгляд, перестраховка. Тем более, причина проблемы - это именно импорт со звёздочкой, и ответственность лежит на том, кто так делает. Это как с доступом к защищенным атрибутам объекта.

2022-02-25 10:29 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-02-25 10:29 UTC, merged