Домашная работа - лекция 8.
IlyaOrlov/PythonCourseATIS pull request #31
Opened 2022-02-26 05:49 UTC by fruittrainings

2022-02-26 19:26 UTC, IlyaOrlov requested changes
Пара небольших комментариев.
Итератор идеальный)

2022-02-26 19:26 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_08/lecture_08_task_03_pep8task.py
> +    def generate_name(self, seed=time()):
Очевидно, здесь предполагался вызов time.time()

2022-02-26 19:26 UTC, IlyaOrlov commented on Practice/frumyantsev/Lecture_08/lecture_08_task_01.py
> +        if item in dct:
Можно немножко упростить: dct[item] = dct.get(item, 0) + 1

2022-02-27 07:35 UTC, fruittrainings commented on Practice/frumyantsev/Lecture_08/lecture_08_task_01.py
> +        if item in dct:
Спасибо, исправил.

2022-02-27 07:37 UTC, fruittrainings commented on Practice/frumyantsev/Lecture_08/lecture_08_task_03_pep8task.py
> +    def generate_name(self, seed=time()):
Исправил.

2022-02-27 07:56 UTC, IlyaOrlov approved these changes
Отлично!

2022-02-27 07:56 UTC, merged