Задание 10_1. 10_1_1 - сервер, 10_1_2 - клиент.
IlyaOrlov/PythonCourseATIS pull request #33
Opened 2022-03-01 13:40 UTC by ZloiGaMeR

Илья, посмотрите пожалуйста задание 1 по 10 лекции.(10_1_1 - клиент, 10_1_2 - сервер)

2022-03-01 20:37 UTC, IlyaOrlov requested changes
Клиент-серверное взаимодействие организовано корректно. Есть пара небольших замечаний.

2022-03-01 20:37 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec10_1_2.py
> +from Lec10_1_1 import coding, gen_dict
Поскольку клиент и сервер обычно запускаются на разных машинах, а тащить весь код сервера на машину клиента не лучшее решение, стоит вынести их общий код в отдельный файл и импортировать этот файл и в сервере, и в клиенте.

2022-03-01 20:37 UTC, IlyaOrlov commented on Practice/a.belyantsev/Lec10_1_2.py
> +secret_list = ["the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"]
Здесь ```if __name__ == "__main__":``` тоже не помешает.

2022-03-02 06:44 UTC, ZloiGaMeR commented on Practice/a.belyantsev/Lec10_1_2.py
> +secret_list = ["the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"]
Хорошо

2022-03-02 06:44 UTC, ZloiGaMeR commented on Practice/a.belyantsev/Lec10_1_2.py
> +from Lec10_1_1 import coding, gen_dict
Хорошо, спасибо!

2022-03-02 08:07 UTC, IlyaOrlov approved these changes
Отлично! Получившееся решение хорошо эмулирует использование шифрования в реальных системах.

2022-03-02 08:16 UTC, merged