Практика 9-1
IlyaOrlov/PythonCourseATIS pull request #34
Opened 2022-03-01 16:31 UTC by ismartynenko

2022-03-01 21:02 UTC, IlyaOrlov requested changes
Есть некоторые замечания и вопросы.

2022-03-01 21:02 UTC, IlyaOrlov commented on Practice/ismartynenko/practice10_1_client.py
> +s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
И здесь, и в сервере лучше убрать код в глобальной области видимости под ```if __name__ == "__main__":```

2022-03-01 21:02 UTC, IlyaOrlov commented on Practice/ismartynenko/practice9_1.py
> +            if start % i == 0:
Если start делится на что-то без остатка, то дальше его проверять не имеет смысла. Поэтому лучше сразу сделать break, иначе (пока дойдет до проверки j != 1) сначала будет лишний раз считаться i*i <= start.

2022-03-01 21:02 UTC, IlyaOrlov commented on Practice/ismartynenko/practice9_1.py
> +        while i*i <= start and j != 1:
Чтоб не считать на каждой итерации i*i, проще отдельно (вне вложенного цикла) посчитать квадратный корень из start и сравнивать его с i.

2022-03-01 21:02 UTC, IlyaOrlov commented on Practice/ismartynenko/practice9_1.py
> +Процессы же не замечают если забыть указать join'''
А как отсутствие join сказывается на **рассчитанном** времени работы процессов?
На самом деле процессы и потоки (даже если не указать join) автоматически сворачиваются при закрытии главного процесса. При этом, в общем случае, они могут не успеть доделать свои задачи.

2022-03-01 21:02 UTC, IlyaOrlov commented on Practice/ismartynenko/practice9_1.py
> +    th1 = threading.Thread(target=find_primes, args=(10000,))
Всё-таки лучше здесь и для процессов использовать списки, чтоб не создавать отдельные переменные для каждого процесса или потока.

2022-03-01 21:02 UTC, IlyaOrlov commented on Practice/ismartynenko/practice9_1.py
> +    print(time.perf_counter() - t_start)
Чей результат в итоге лучше, чей хуже, и почему?
Рекомендую также для сравнения, попробовать то же самое на чуть больших диапазонах:
find_primes(1000000)
find_primes(2000000, 1000001)
find_primes(3000000, 2000001)

2022-03-02 10:09 UTC, IlyaOrlov requested changes
Оставил небольшой комментарий. Ну и ожидается наполнение методов select и execute класса SqlWrapper.

2022-03-02 10:09 UTC, IlyaOrlov commented on Practice/ismartynenko/practice9_1.py
> +        while i <= n and j != 1:
j != 1 уже лишняя проверка, т.к. добавлен break.

2022-03-02 10:09 UTC, IlyaOrlov commented on Practice/ismartynenko/practice9_1.py
> +Полагаю что процессы/потоки медленнее с join() потому что уходит время на их завершение.'''
Не только на завершение, но и на создание. Временные затраты на эти операции сопоставимы с затратами на сами расчеты. Однако, если увеличить диапазоны (и соответственно временные затраты на расчеты), то процессы покажут лучший результат.

2022-03-02 13:47 UTC, ismartynenko commented
> Оставил небольшой комментарий. Ну и ожидается наполнение методов select и execute класса SqlWrapper.

Я чето запутался. подскажите в корне неверно, или в деталях.
столкнулся с Parameter 'self' unfilled.

2022-03-02 14:20 UTC, IlyaOrlov commented
> > Оставил небольшой комментарий. Ну и ожидается наполнение методов select и execute класса SqlWrapper.
> 
> Я чето запутался. подскажите в корне неверно, или в деталях. столкнулся с Parameter 'self' unfilled.

В деталях) С менеджером контекста надо немножко по-другому работать:
```python
with SqlWrapper() as sqw:
    sqw.execute(...)
    sqw.select(...)
```

2022-03-09 14:44 UTC, IlyaOrlov requested changes

2022-03-09 14:44 UTC, IlyaOrlov commented on Practice/ismartynenko/practice11_1.py
> +        print(json.dumps(cur.fetchall()))
return здесь лучше, т.к. позволяет использовать результат функции select

2022-03-09 14:44 UTC, IlyaOrlov commented on Practice/ismartynenko/practice11_1.py
> +        _db_name = "films.db"
Лучше передавать имя базы, как аргумент метода ```__init__```,  тогда SqlWrapper можно будет применять к разным базам.

2022-03-10 06:51 UTC, IlyaOrlov commented on Practice/ismartynenko/practice11_1.py
> +        self.conn = sqlite3.connect(self.db_name)
А вот коннектиться к базе лучше в ```__enter__```, раз уж мы закрываем это соединение в ```__exit__```.

2022-03-11 15:56 UTC, IlyaOrlov requested changes
Есть замечания по Money. С остальным всё ОК.

2022-03-11 15:56 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_10.py
> +        return f"{self.sum_rub},{self.sum_kop}"
Лучше, чтоб ```__add__``` и ему подобные методы возвращали значение того же типа, к которому метод относится. Складываем числа - получаем число, складываем строки - получаем строку, складываем экземпляры Money - получаем экземпляр Money. Помимо того, что это логично, такой подход позволяет складывать многократно: s = s1 + s2 + s3 + s4 и т.д.

2022-03-11 15:56 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_10.py
> +        if self.sum_kop >= 10:
Может, больше 100?

2022-03-13 18:32 UTC, IlyaOrlov requested changes
Остались замечания по реализованным методам, ожидается реализация методов сравнения.

2022-03-13 18:32 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_10.py
> +        return res
Нет. Здесь нужно вернуть Money(res). То же самое в ```__sub__``.

2022-03-13 18:32 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_10.py
> +        res = (self.num * 100) / (other.num * 100)
Зачем и числитель, и знаменатель умножать на 100, и что будет, если знаменатель окажется нулём?
Тут стоит предусмотреть два варианта возвращаемого значения: если мы Money делим на число (например, делим деньги на количество человек) - получаем Money (сколько денег достанется каждому); если мы Money делим на Money (например, считаем на сколько человек мы можем поделить заданную сумму, если каждому отдадим other.num) - получаем число (количество человек, которым достанутся деньги).

2022-03-14 09:35 UTC, IlyaOrlov requested changes
С фабрикой танков все отлично. По Money остались небольшие замечания.

2022-03-14 09:35 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_10.py
> +            return "can't divide by zero"
Лучше ошибку напечатать, а вернуть None, или пусть просто исключение выбрасывается. Пользователь класса Money будет удивлен, получив при делении строку)

2022-03-14 09:35 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_10.py
> +            return Money(res)
Если мы Money делим на Money, то вроде как должны получить число. Число логически...

2022-03-14 09:35 UTC, IlyaOrlov commented on Practice/ismartynenko/exam_10.py
> +        if self.num < other.num:
Во всех логических операторах всё тело можно записать в одну строку. Например, ```return self.num < other.num```

2022-03-16 20:34 UTC, ismartynenko commented on Practice/ismartynenko/exam_10.py
> +        if self.num < other.num:
Как раз в фабрике танков позже увидел, у нас в классе метод сравнения мощности так был переопределен

2022-03-17 07:33 UTC, IlyaOrlov requested changes
С Money все ОК. Есть предложение по оптимизации opencv.py

2022-03-17 07:33 UTC, IlyaOrlov commented on Practice/ismartynenko/opencv_task/opencv.py
> +    NUM_SIZE = 42
По строкам 68-82: как всегда, оригинально) Только проводить множество сравнений картинок неэффективно. Лучше просто сопоставлять найденный радиус с отдельными диапазонами. Границы диапазонов можно сохранить в отсортированном по возрастанию виде в кортеж.

2022-03-17 13:56 UTC, ismartynenko commented on Practice/ismartynenko/opencv_task/opencv.py
> +    NUM_SIZE = 42
Ну если надо что то просто сильно усложнить там где это не нужно и  объяснить заказчику почему вышло так дорого - обращайтесь)
На ровном месте... распознавание картинок))) куча вычислений, подготовка образцов для сравнений
Ну зато немного про OpenCV почитал

2022-03-18 16:41 UTC, IlyaOrlov approved these changes

2022-03-18 16:42 UTC, IlyaOrlov commented on Practice/ismartynenko/opencv_task/opencv.py
> +    NUM_SIZE = 42
Да, побольше с OpenCV поэкспериментировали) Это тоже полезно!

2022-03-18 16:42 UTC, merged