homework lectures1
IlyaOrlov/PythonCourseATIS pull request #4
Opened 2021-12-22 16:40 UTC by iana-golovchenko

2021-12-22 19:05 UTC, IlyaOrlov requested changes

2021-12-22 19:05 UTC, IlyaOrlov commented on Practice/i.golovchenko/L1.Practice4.py
> +os.system('echo data') #не соображу как сделать чтобы переменная передавала значение в функцию систем
Можно так: ```os.system(f"echo {data}")``` Но зачем os.system, если есть print?

2021-12-22 19:05 UTC, IlyaOrlov commented on Practice/i.golovchenko/L1.Practice7.py
> +        f = open(output, 'r')
В строках 25-26 поменялись отступы. В них выполняется запись содержимого контейнера self.map в файл output. Контейнер заполняется в цикле for path, mp3 in mp3s:. Если строки 26-27 внести в цикл, то содержимое файла будет перезаписываться многократно при каждом изменении self.map. Если же их вынести из цикла, то мы просто однократно запишем в файл итоговое содержимое self.map. Что лучше?

2021-12-27 07:51 UTC, iana-golovchenko commented on Practice/i.golovchenko/L1.Practice4.py
> +os.system('echo data') #не соображу как сделать чтобы переменная передавала значение в функцию систем
Первая мысль, когда я прочитала задание и увидела "Echo" - что нужно выполнить работу, через команду bash, полезла в гугл как работать в python c командами bash, сейчас поняла, что требовалось другое

2021-12-27 07:52 UTC, iana-golovchenko commented on Practice/i.golovchenko/L1.Practice7.py
> +        f = open(output, 'r')
в строчках 25-26 - удалила по 1 отступу (4 пробела) , чтобы содержимое контейнера записалось только 1 раз в файл

2021-12-27 11:50 UTC, IlyaOrlov commented on Practice/i.golovchenko/L1.Practice4.py
> +os.system('echo data') #не соображу как сделать чтобы переменная передавала значение в функцию систем
ОК. Зато еще одну возможность Python освоили)

2021-12-27 11:53 UTC, IlyaOrlov commented on Practice/i.golovchenko/L1.Practice7.py
> +        f = open(output, 'r')
Отлично. Только еще строки 17-26 надо все вместе вправо сдвинуть, т.к. они все входят в функцию rename (по-другому в теле класса Scheduler не получится).

2021-12-27 11:59 UTC, IlyaOrlov requested changes
Все хорошо! Есть только небольшие замечания.
Вывод на консоль лучше делать с помощью форматных строк ```print(f"Value: {value}")```
Так нагляднее: проще представить, как вывод будет выглядеть на консоли пользователя.

2021-12-27 11:59 UTC, IlyaOrlov commented on Practice/i.golovchenko/L2.Practice2.py
> +def max(a, b):
В Python есть стандартная функция max. Для своих функций стоит использовать имена, отличные от зарезервированных. PyCharm обычно подсказывает, когда встречаются такие совпадения.

2022-01-03 16:58 UTC, iana-golovchenko commented on Practice/i.golovchenko/L1.Practice7.py
> +        f = open(output, 'r')
по этому же принципу подвинула строчки 33-39, т.к они входят в функцию restore - надеюсь верно

2022-01-03 16:59 UTC, iana-golovchenko commented on Practice/i.golovchenko/L2.Practice2.py
> +def max(a, b):
Исправила 1 и 2 замечание

2022-01-03 17:13 UTC, IlyaOrlov commented on Practice/i.golovchenko/L1.Practice7.py
> +        f = open(output, 'r')
Согласен)

2022-01-03 17:20 UTC, IlyaOrlov requested changes

2022-01-03 17:20 UTC, IlyaOrlov commented on Practice/i.golovchenko/L2.Practice2.py
> +print(return_max(num1, num2))
Здесь есть нюанс. input возвращает значение типа строка, поэтому если пользовать введет 9 и 10, то return_max вернет 9 (т.к. сравнение для строк будет выполняться посимвольно). **К return_max претензий нет**: что ей передают, то она и сравнивает. Но смущает слово "число" в input, т.к. это вроде как означает, что дальнейшие действия должны выполняться именно с числами, а не строками.

2022-01-09 09:27 UTC, iana-golovchenko commented on Practice/i.golovchenko/L2.Practice2.py
> +print(return_max(num1, num2))
мне правда подсказали, что если добавить int перед input  будет возвращаться целое число в десятичной системе счисления

2022-01-09 09:37 UTC, IlyaOrlov commented on Practice/i.golovchenko/L2.Practice2.py
> +print(return_max(num1, num2))
Да, подсказали правильно) Также можно и на этом этапе строки в числа преобразовывать: ```print(return_max(int(num1), int(num2)))``` В любом случае мы здесь полагаемся на то, что пользователь вводит именно цифры, а не буквы, или какие-то другие символы. Но в условиях данной задачи такое допущение приемлемо.

2022-01-09 09:37 UTC, IlyaOrlov approved these changes
Теперь все отлично!

2022-01-09 09:37 UTC, merged