Fedor branch 02
IlyaOrlov/PythonCourseATIS pull request #6
Opened 2022-01-01 17:19 UTC by fruittrainings

Please review tasks 1 and 2 of lecture 2.

2022-01-01 20:48 UTC, IlyaOrlov reviewed
Файлы lecture_02_task_01.py и lecture_02_task_02.py пустые. Так и задумано?

2022-01-01 21:07 UTC, fruittrainings commented
Не были пустые когда отправлял и не пустые сейчас у меня на машине. Не пойму в чем дело.

2022-01-01 21:11 UTC, IlyaOrlov commented
> Не были пустые когда отправлял и не пустые сейчас у меня на машине. Не пойму в чем дело.

У вас два бранча: fedor_branch_01 и fedor_branch_02. Может, изменения сделаны на одном, а Pull Request сделан для другого?

2022-01-01 21:14 UTC, fruittrainings commented
Нет, обе операции выполнены для fedor_branch_02

2022-01-01 21:16 UTC, fruittrainings commented
![Screenshot 2022-01-02 001503](https://user-images.githubusercontent.com/96711937/147860341-b20b32aa-f7ed-4ec1-85ee-1864d2e48495.png)

2022-01-01 21:23 UTC, fruittrainings commented
Формально поменял оба файла (добавил #) и после этого смог их повторно добавить.

2022-01-01 21:23 UTC, IlyaOrlov commented
> ![Screenshot 2022-01-02 001503](https://user-images.githubusercontent.com/96711937/147860341-b20b32aa-f7ed-4ec1-85ee-1864d2e48495.png)

Судя по скриншоту, последние изменения в этих файлах не были добавлены/закоммичены (иначе гит бы отображал их зеленым). Теперь все ОК. Вижу изменения.

2022-01-01 21:24 UTC, fruittrainings commented
Возможно, я пропустил какую-то из операций. Теперь вижу, что оба файла запушились.

2022-01-01 21:26 UTC, fruittrainings commented
Почему-то у меня также запушился файл new_file.py хотя до этого я добавлял его в .gitignore

2022-01-01 21:34 UTC, IlyaOrlov requested changes

2022-01-01 21:34 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_02_task_01.py
> +max_value = lambda x = input("Key in value1: "), y = input("Key in value2: "): print(max(x,y))
Замечания по обоим файлам:
1. lambda еще называют безымянными функциями. В тех случаях, когда для lambda-функции требуется  указать ссылающуюся на нее переменную, лучше, на самом деле, использовать обычную функцию (это обычно подсказывает PyCharm).
2. "Функция, принимающая два числа" - это функция с двумя формальными параметрами. Такая функция будет более универсальной, чем функция, у которой эти числа задаются непосредственно в ее теле. Ей можно передать, как предустановленные данные, так и данные из файла, и с клавиатуры.
3. В данном задании не нужно использовать стандартную функцию max. Для двух чисел лучше использовать условный оператор.

2022-01-01 21:35 UTC, IlyaOrlov commented
> .gitignore

Это не он запушился. Это как раз измененный .gitignore

2022-01-01 22:00 UTC, fruittrainings commented
Не понимаю, в .gitignore я добавлял два файла, но почему-то в списке измененных файлов вижу только один. Спасибо. Переписал функции в обычном виде. По поводу ваших замечаний:
1. Правильно ли я поинмаю, что раз лямбда-функции безымянные, то их нельзя переиспользовать? В таком случае, какой от них толк - получается это обычное выражение. А если можно переиспользовать, то как?
2. А как в функцию вида f(x, y) можно передавать данные из файла или с клавиатуры?
3. Поскольку в условии задания не рассматривался случай равенства чисел, то и я не стал включать соответствующую ветку в код.

2022-01-01 22:42 UTC, IlyaOrlov commented
> Не понимаю, в .gitignore я добавлял два файла, но почему-то в списке измененных файлов вижу только один. Спасибо. Переписал функции в обычном виде. По поводу ваших замечаний:
> 
> 1. Правильно ли я поинмаю, что раз лямбда-функции безымянные, то их нельзя переиспользовать? В таком случае, какой от них толк - получается это обычное выражение. А если можно переиспользовать, то как?
> 2. А как в функцию вида f(x, y) можно передавать данные из файла или с клавиатуры?
> 3. Поскольку в условии задания не рассматривался случай равенства чисел, то и я не стал включать соответствующую ветку в код.

0. А какие еще файлы вы добавляли в .gitignore? Pull Request показывает, что вы добавили в файл .gitignore строку new_file.py. Собственно, этого файла new_file.py в Pull Request'е и нет. Вроде все логично.
1. Обычно lambda-функции используют для компактной передачи динамических выражений в другие функции. Например, чтоб отсортировать следующий список по модулям элементов, нужно указать сортирующему методу sort, как определять эти модули. Для этого в методе sort предусмотрен параметр key, в который можно передать **только функцию** (так устроен sort) для вычисления ключа сортировки. lambda позволяет задать этот ключ в одно выражение.
```python
lst = [1, -2, 4, -3]
lst.sort(key=lambda x: -x if x < 0 else x)
print(lst)
```
2. С клавиатуры:
```python
x = int(input('Введите первое число: '))
y = int(input('Введите второе число: '))
max_value(x, y)
```
Из файла myfile:
```python
with open('myfile') as f:
    x = int(f.readline())
    y = int(f.readline())
max_value(x, y)
```
При этом код самой функции max_value остается без изменений.
3. ОК, но одинаковые числа все равно могут быть переданы. Отсутствие указаний на это в задании оставляет обработку такого случая на ваше усмотрение. Функция с return вернет в этом случае None (это нормально, хотя лучше вернуть None явно), а вот функция с print вообще ничего не выведет (ни ошибки, ни какой-либо информации), и это уже нехорошо, и следует скорректировать.

2022-01-01 23:22 UTC, fruittrainings commented
0. В .gitignore еще добалял name_gen.py.
1. и 2. Спасибо.
3. Скорректирую функции.

2022-01-02 02:23 UTC, fruittrainings commented
Разобрался с пунктом 0. Один из файлов не отображался в .gitignore так как после его добавления в .gitignore я не сделал "git add .gitignore", предполагая, что это произойдет автоматически.

2022-01-02 09:10 UTC, IlyaOrlov commented
> Разобрался с пунктом 0. Один из файлов не отображался в .gitignore так как после его добавления в .gitignore я не сделал "git add .gitignore", предполагая, что это произойдет автоматически.

Вот поэтому работать с git через PyCharm удобней. Последний показывает, что конкретно входит в коммит и пуш.

2022-01-02 09:12 UTC, IlyaOrlov approved these changes
Теперь все отлично!!!

2022-01-02 09:12 UTC, merged