Fedor branch 03
IlyaOrlov/PythonCourseATIS pull request #7
Opened 2022-01-02 21:34 UTC by fruittrainings

Пока по классам больше вопросов, чем ответов.

2022-01-02 22:18 UTC, IlyaOrlov requested changes
В целом задание выполнено правильно! Если только небольшие замечания.
Кстати, все задания можно делать и на одном бранче)

2022-01-02 22:18 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_02_task_03.py
> +# не понятно, почему при создании нового объекта дочернего класса HeavyTank не потребовалось
Потому что метод \_\_init\_\_ дочернего класса полностью переопределяет \_\_init\_\_ родительского. Нужно явно вызвать родительский метод из дочернего следующим образом:
```python
class HeavyTank(Tank):
    def __init__(self, load_regular, load_explosive, model, technical_state, extra_armor):
        super().__init__(load_regular, load_explosive, model, technical_state)
        self.extra_armor = extra_armor
```
Мы еще детально поговорим про наследование в Python на занятиях, но хорошо, что вы ознакомились с проблематикой уже сейчас.

2022-01-02 22:18 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_02_task_03.py
> +    def __init__(self, load_regular : int, load_explosive : int, model = 'T34', technical_state = '10'):
Небольшое замечание по стилю здесь и в стр.47 и 66: при перечислении формальных аргументов со значениями по умолчанию пробелы вокруг "=" не ставятся (1). Также нужно убрать пробел перед ":" (2).
[pep8 - 1](https://www.python.org/dev/peps/pep-0008/#:~:text=Don%27t%20use%20spaces%20around%20the%20%3D%20sign%20when%20used%20to%20indicate%20a%20keyword%20argument%2C%20or%20when%20used%20to%20indicate%20a%20default%20value%20for%20an%20unannotated%20function%20parameter%3A)
[pep8 - 2](https://www.python.org/dev/peps/pep-0008/#:~:text=Function%20annotations%20should%20use%20the%20normal%20rules%20for%20colons%20and%20always%20have%20spaces%20around%20the%20%2D%3E%20arrow%20if%20present.%20(See%20Function%20Annotations%20below%20for%20more%20about%20function%20annotations.)%3A)

2022-01-02 22:18 UTC, IlyaOrlov commented on Practice/frumyantsev/lecture_02_task_03.py
> +        return None
\_\_init\_\_ - это особый случай, как и все "магические" методы. У них есть определенные ограничения на то, что они могут принимать, и что могут возвращать. В частности, из \_\_init\_\_ ничего вернуть нельзя. Поэтому писать return здесь не нужно.

2022-01-02 23:39 UTC, fruittrainings commented on Practice/frumyantsev/lecture_02_task_03.py
> +    def __init__(self, load_regular : int, load_explosive : int, model = 'T34', technical_state = '10'):
Спасибо, исправил.

2022-01-02 23:39 UTC, fruittrainings commented on Practice/frumyantsev/lecture_02_task_03.py
> +        return None
Спасибо, исправил.

2022-01-02 23:39 UTC, fruittrainings commented on Practice/frumyantsev/lecture_02_task_03.py
> +# не понятно, почему при создании нового объекта дочернего класса HeavyTank не потребовалось
Спасибо, исправил.

2022-01-02 23:45 UTC, fruittrainings commented
Мне показалось удобно разбивать на мелкие бранчи. А как принято в отрасли? И как лучше в рамках курса: 1 бранч на весть курс, или один бранч, например, на все задания из одной лекции?

2022-01-03 08:29 UTC, IlyaOrlov commented
> Мне показалось удобно разбивать на мелкие бранчи. А как принято в отрасли? И как лучше в рамках курса: 1 бранч на весть курс, или один бранч, например, на все задания из одной лекции?

В отрасли обычно на отдельные задачи создаются отдельные бранчи, правда, задачи эти достаточно крупные. В рамках курсах стоит делать, как вам удобней. Несколько бранчей позволяют принимать и мержить в main задачи независимо друг от друга. Но когда бранчей много, в них легче запутаться (хотя можно удалять старые бранчи).

2022-01-03 08:31 UTC, IlyaOrlov requested changes
Все отлично! Классы созданы корректно с разнообразием атрибутов и методов, приведены примеры объектов.

2022-01-03 08:32 UTC, IlyaOrlov approved these changes

2022-01-03 08:32 UTC, merged